export const combinedQuizCategories = [
    "Mathematics",
    "English Language & Literature",
    "Science (General)",
    "World History",
    "Geography",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Art & Music",
    "Physical Education",
    "Health & Nutrition",
    "Environmental Studies",
    "Social Studies",
    "Foreign Languages",
    "Economics & Business Studies",
    "Psychology",
    "Civic Education",
    "Classical Studies",
    "Creative Writing",
    "Drama & Theater Arts",
    "Debate & Public Speaking",
    "Astronomy",
    "Robotics & Engineering",
    "Mythology & Folklore",
    "Film Studies",
    "Graphic Design",
    "Philosophy",
    "Statistics",
    "Government & Politics"
  ];
  